---
- name: EC2-test
  hosts: localhost
  gather_facts: no
  vars:
    region: "ap-south-1"
    ami_id: "ami-087d1c9a513324697"  # Example AMI ID (Ubuntu 20.04 LTS)
    instance_type: "t3.micro"
    key_name: "Linux1"  # Replace with your actual SSH key pair name
    security_group_name: "my-sg1"
    subnet_id: "subnet-0eca1110716d8aa58"  # Replace with your subnet ID
 
  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Security"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"  # SSH access
        state: present
      register: sg
 
    - name: EC2 instance
      amazon.aws.ec2_instance:
        name: "MyEC2Instance"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        security_groups:
          - "{{ sg.group_name }}"
        subnet_id: "{{ subnet_id }}"
        count: 1
        wait: yes
      register: ec2_instance