---
- name: Launch EC2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: sg
      amazon.aws.ec2_group:
        name: my-ansible-sg
        description: Security group
        region: ap-south-1
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
        state: present
      register: ec2_sg

    - name: EC2 test
      amazon.aws.ec2_instance:
        name: test3-instance
        key_name: Linux1
        instance_type: t3.micro
        image_id: ami-07f07a6e1060cd2a8  # Update with a valid AMI ID for your region
        wait: yes
        count: 1
        region: ap-south-1
        security_group: my-ansible-sg
        state: running
      register: ec2_instance

    - name: Print public IP
      debug:
        msg: "Public IP: {{ ec2_instance.instances[0].public_ip_address }}"
