---
- name: Create a Pod in Kubernetes
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create a Pod in Kubernetes
      k8s:
        state: present
        kubeconfig: ~/.kube/config
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: my-pod
            namespace: default
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
