---
- name: Create a Pod in Kubernetes
  hosts: all
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create a simple NGINX Pod
      k8s:
        state: present
        kubeconfig: /home/ubuntu/.kube/config
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: anjali-pod
            namespace: default
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
